global:
  scrape_interval:     15s	# 采集数据的时间间隔,默认15s
  evaluation_interval: 15s	# 评估规则的间隔时间,默认15s
alerting:					# alertmanagers用于告警
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093
rule_files:					# 规则配置文件
  # - "first_rules.yml"
  # - "second_rules.yml"
scrape_configs:				# 抓取哪里的数据到TSDB(时序数据库)
  - job_name: prometheus
    metrics_path: '/prometheus/metrics'
    static_configs:
    - targets: ['127.0.0.1:9090']
  - job_name: consul
    scrape_interval: 15s
    scrape_timeout: 5s
    consul_sd_configs:
      - server: '192.168.225.128:8500' # 修改你consul服务所在的ip地址
        services: ["Linux"] # 这里是匹配注册到consul中的服务名